### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by hugo-vrijswijk** [rowdyrabouw/8.bit#2]
There is no license. Am I allowed to use this project? I don't know and I'm feeling confused

**Comment by rowdyrabouw** [comment]
There is a license, see https://github.com/rowdyrabouw/8.bit/blob/ea044507449202add1f216848d16d0522d18f2b8/package.json#L18

**Comment by hugo-vrijswijk** [comment]
I said nothing. My confusion is gone and I can see clearly now
